[[entry]]
played_at = "2026-07-09T02:45:43Z"
path = "spotify:track:2vjY3jGKElvqXoaGNEuYef"
title = "怪物"
artist = "YOASOBI"
album = "THE BOOK 2"
year = 2021
track_number = 6
duration_secs = 205

[[entry]]
played_at = "2026-07-09T02:42:18Z"
path = "spotify:track:4NkCOiUOXDXrPWeuQJE6cl"
title = "Кустурица"
artist = "Bratya Grim"
album = "Братья Грим"
year = 2005
track_number = 12
duration_secs = 173

[[entry]]
played_at = "2026-07-09T02:38:43Z"
path = "spotify:track:2qRMnItMLesizxbPqIwcSm"
title = "Mai"
artist = "Videoclub"
album = "Euphories"
year = 2021
track_number = 5
duration_secs = 217

[[entry]]
played_at = "2026-07-09T02:35:08Z"
path = "spotify:track:1hAloWiinXLPQUJxrJReb1"
title = "アイドル"
artist = "YOASOBI"
album = "THE BOOK 3"
year = 2023
track_number = 7
duration_secs = 211

[[entry]]
played_at = "2026-07-09T02:31:36Z"
path = "spotify:track:6mniISeqwqmTW7mcpaebAq"
title = "EDM"
artist = "Big Baby Tape, Aarne, Платина"
album = "PEEKABOO"
year = 2024
track_number = 9
duration_secs = 163

[[entry]]
played_at = "2026-07-09T02:28:53Z"
path = "spotify:track:7wIeCl9aqbra6O2D9fGygg"
title = "ДЭФО"
artist = "the pak"
album = "ДЭФО"
year = 2026
track_number = 1
duration_secs = 160

[[entry]]
played_at = "2026-07-09T02:26:13Z"
path = "spotify:track:1ucsBUEWBNEObyW4KBlsfo"
title = "Пальмира"
artist = "Luna"
album = "Транс"
year = 2019
track_number = 8
duration_secs = 253

[[entry]]
played_at = "2026-07-09T02:22:00Z"
path = "spotify:track:1chmVQLbEPT5890S0X55pe"
title = "TEST ME"
artist = "CHANMINA"
album = "TEST ME"
year = 2026
track_number = 1
duration_secs = 171

[[entry]]
played_at = "2026-07-09T02:19:09Z"
path = "spotify:track:0eAuGrXyGFYwur9ARUe7LJ"
title = "Earrings"
artist = "Malcolm Todd"
album = "Sweet Boy"
year = 2024
track_number = 1
duration_secs = 151

[[entry]]
played_at = "2026-07-09T02:16:37Z"
path = "spotify:track:4EBQ9JamSD7TPpNAtfBhwi"
title = "Mystery Girl"
artist = "Housecall"
album = "Mystery Girl"
year = 2018
track_number = 1
duration_secs = 176

[[entry]]
played_at = "2026-07-09T02:13:41Z"
path = "spotify:track:1dpHnn6eh4Pz55UproSdJv"
title = "так похуй"
artist = "madk1d"
album = "sexyswag"
year = 2025
track_number = 1
duration_secs = 108

[[entry]]
played_at = "2026-07-09T02:11:53Z"
path = "spotify:track:67llqAFIyR6d6JMjDImDyU"
title = "8 миля"
artist = "madk1d, VILLIAN"
album = "8 миля"
year = 2026
track_number = 1
duration_secs = 115

[[entry]]
played_at = "2026-07-09T02:09:57Z"
path = "spotify:track:7B4napIhOn1s4qnwgcXBCl"
title = "Лига Опасного Интернета"
artist = "Oxxxymiron"
album = "Лига Опасного Интернета"
year = 2023
track_number = 1
duration_secs = 140

[[entry]]
played_at = "2026-07-09T02:08:16Z"
path = "spotify:track:1IqRoFm0NHj23m8L1CMqw2"
title = "Forever Young"
artist = "FACE"
album = "VLONE"
year = 2016
track_number = 5
duration_secs = 191

[[entry]]
played_at = "2026-07-09T02:05:04Z"
path = "spotify:track:3go07nYMXYvGgUJsiitDyu"
title = "WHITE LIKE ROLLS"
artist = "FORTUNA 812"
album = "WHITE LIKE ROLLS"
year = 2026
track_number = 1
duration_secs = 125

[[entry]]
played_at = "2026-07-09T02:02:58Z"
path = "spotify:track:4fQVQKIiidREPI0MhFEuDn"
title = "My Moon My Man"
artist = "Feist"
album = "The Reminder"
year = 2007
track_number = 3
duration_secs = 228

[[entry]]
played_at = "2026-07-09T01:59:10Z"
path = "spotify:track:6DKSK32WwzBMZ0qAq28Zon"
title = "Hotel Room"
artist = "Ax and the Hatchetmen"
album = "So Much To Tell You"
year = 2025
track_number = 8
duration_secs = 148

[[entry]]
played_at = "2026-07-09T01:30:56Z"
path = "spotify:track:1zFbBrZmJr1Z49HYe84dBg"
title = "Harvey"
artist = "Her's"
album = "Invitation to Her's"
year = 2018
track_number = 1
duration_secs = 211

[[entry]]
played_at = "2026-07-09T01:27:26Z"
path = "spotify:track:4S4QJfBGGrC8jRIjJHf1Ka"
title = "Pain"
artist = "PinkPantheress"
album = "to hell with it"
year = 2021
track_number = 1
duration_secs = 98

[[entry]]
played_at = "2026-07-09T01:25:51Z"
path = "spotify:track:2gagUqVz8Np58Lvxv179J6"
title = "Поцелуи"
artist = "Luna"
album = "Остров свободы"
year = 2017
track_number = 3
duration_secs = 242

[[entry]]
played_at = "2026-07-09T01:21:48Z"
path = "spotify:track:7hZLv9vCEoRBxOjyGEoih0"
title = "Перепутала"
artist = "SEREBRO"
album = "СИЛА ТРЁХ"
year = 2016
track_number = 4
duration_secs = 215

[[entry]]
played_at = "2026-07-09T01:18:13Z"
path = "spotify:track:2K373m3ampRHhiR1x5NfBk"
title = "Фонари"
artist = "Gorod 312"
album = "Вне зоны доступа"
year = 2006
track_number = 13
duration_secs = 173

[[entry]]
played_at = "2026-07-09T01:15:20Z"
path = "spotify:track:2vjY3jGKElvqXoaGNEuYef"
title = "怪物"
artist = "YOASOBI"
album = "THE BOOK 2"
year = 2021
track_number = 6
duration_secs = 205

[[entry]]
played_at = "2026-07-09T01:11:55Z"
path = "spotify:track:4NkCOiUOXDXrPWeuQJE6cl"
title = "Кустурица"
artist = "Bratya Grim"
album = "Братья Грим"
year = 2005
track_number = 12
duration_secs = 173

[[entry]]
played_at = "2026-07-09T01:09:02Z"
path = "spotify:track:2pQZkGyZvrep3yAAlBKsdX"
title = "Ночь"
artist = "Andrey Gubin"
album = "Мальчик бродяга"
year = 1995
track_number = 2
duration_secs = 222

[[entry]]
played_at = "2026-07-09T01:05:21Z"
path = "spotify:track:3ALWsEki6RCoDtyfkMpQZ8"
title = "Хочется"
artist = "Gradusy"
album = "Градус 100"
year = 2016
track_number = 3
duration_secs = 180

[[entry]]
played_at = "2026-07-09T01:02:21Z"
path = "spotify:track:6DCurv9yITq1sreCs5jArc"
title = "Сегодня"
artist = "Flëur"
album = "Всё вышло из\u200b-\u200bпод контроля"
year = 2006
track_number = 11
duration_secs = 257

[[entry]]
played_at = "2026-07-09T00:58:03Z"
path = "spotify:track:4wwqUoX7OweabhkpP2kaTS"
title = "ХОЧЕШЬ?"
artist = "Zemfira"
album = "ПРОСТИ МЕНЯ МОЯ ЛЮБОВЬ"
year = 2000
track_number = 4
duration_secs = 198

[[entry]]
played_at = "2026-07-09T00:54:47Z"
path = "spotify:track:1kHV1UUB8TA0dmRgwYrVFZ"
title = "Я всегда помню о главном"
artist = "Gradusy"
album = "Чувство ловкости"
year = 2014
track_number = 5
duration_secs = 213

[[entry]]
played_at = "2026-07-09T00:51:13Z"
path = "spotify:track:12NAMTSAP5gphJROLrcT12"
title = "Это было в России"
artist = "Monetochka"
album = "Молитвы. Анекдоты. Тосты."
year = 2024
track_number = 1
duration_secs = 193

[[entry]]
played_at = "2026-07-09T00:48:01Z"
path = "spotify:track:0tdRgufTWFxk2QgYyIifQH"
title = "Папина любовница"
artist = "Monetochka"
album = "Декоративно-прикладное искусство"
year = 2020
track_number = 2
duration_secs = 208

[[entry]]
played_at = "2026-07-09T00:44:32Z"
path = "spotify:track:4IjiY0sShCYUEEoOSEwsgY"
title = "Каждый раз"
artist = "Monetochka"
album = "Раскраски для взрослых"
year = 2018
track_number = 2
duration_secs = 208

[[entry]]
played_at = "2026-07-09T00:41:04Z"
path = "spotify:track:7vBW7vVdCDxFa0UeVPM549"
title = "Научиться бы не париться"
artist = "Gradusy"
album = "Научиться бы не париться"
year = 2012
track_number = 1
duration_secs = 208

[[entry]]
played_at = "2026-07-09T00:37:38Z"
path = "spotify:track:4UWBuck7q0VeKYiHrwoqnU"
title = "Тёплые коты"
artist = "Flëur"
album = "Эйфория"
year = 2008
track_number = 6
duration_secs = 251

[[entry]]
played_at = "2026-07-08T00:14:26Z"
path = "spotify:track:1hAloWiinXLPQUJxrJReb1"
title = "アイドル"
artist = "YOASOBI"
album = "THE BOOK 3"
year = 2023
track_number = 7
duration_secs = 211

[[entry]]
played_at = "2026-07-08T00:11:24Z"
path = "spotify:track:4NkCOiUOXDXrPWeuQJE6cl"
title = "Кустурица"
artist = "Bratya Grim"
album = "Братья Грим"
year = 2005
track_number = 12
duration_secs = 173

[[entry]]
played_at = "2026-07-08T00:08:31Z"
path = "spotify:track:2pQZkGyZvrep3yAAlBKsdX"
title = "Ночь"
artist = "Andrey Gubin"
album = "Мальчик бродяга"
year = 1995
track_number = 2
duration_secs = 222

[[entry]]
played_at = "2026-07-07T23:55:53Z"
path = "spotify:track:7vBW7vVdCDxFa0UeVPM549"
title = "Научиться бы не париться"
artist = "Gradusy"
album = "Научиться бы не париться"
year = 2012
track_number = 1
duration_secs = 208

[[entry]]
played_at = "2026-07-07T23:52:27Z"
path = "spotify:track:4UWBuck7q0VeKYiHrwoqnU"
title = "Тёплые коты"
artist = "Flëur"
album = "Эйфория"
year = 2008
track_number = 6
duration_secs = 251

[[entry]]
played_at = "2026-07-07T23:48:15Z"
path = "spotify:track:5WDLRQ3VCdVrKw0njWe5E5"
title = "Careless Whisper"
artist = "George Michael"
album = "Ladies & Gentlemen"
year = 1998
track_number = 3
duration_secs = 300

[[entry]]
played_at = "2026-07-07T23:43:15Z"
path = "spotify:track:7pBzCp7qNLlsH6rzEFkSwN"
title = "FREAKED OUT"
artist = "Fat Papi, prodshushy"
album = "FREAKED OUT"
year = 2026
track_number = 1
duration_secs = 158

[[entry]]
played_at = "2026-07-07T22:08:12Z"
path = "spotify:track:7pBzCp7qNLlsH6rzEFkSwN"
title = "FREAKED OUT"
artist = "Fat Papi, prodshushy"
album = "FREAKED OUT"
year = 2026
track_number = 1
duration_secs = 158

[[entry]]
played_at = "2026-07-05T18:40:16Z"
path = "spotify:track:4NkCOiUOXDXrPWeuQJE6cl"
title = "Кустурица"
artist = "Bratya Grim"
album = "Братья Грим"
year = 2005
track_number = 12
duration_secs = 173

[[entry]]
played_at = "2026-07-05T18:27:46Z"
path = "spotify:track:4wwqUoX7OweabhkpP2kaTS"
title = "ХОЧЕШЬ?"
artist = "Zemfira"
album = "ПРОСТИ МЕНЯ МОЯ ЛЮБОВЬ"
year = 2000
track_number = 4
duration_secs = 198

[[entry]]
played_at = "2026-07-05T18:10:29Z"
path = "spotify:track:4NkCOiUOXDXrPWeuQJE6cl"
title = "Кустурица"
artist = "Bratya Grim"
album = "Братья Грим"
year = 2005
track_number = 12
duration_secs = 173

[[entry]]
played_at = "2026-07-05T18:06:46Z"
path = "spotify:track:2pQZkGyZvrep3yAAlBKsdX"
title = "Ночь"
artist = "Andrey Gubin"
album = "Мальчик бродяга"
year = 1995
track_number = 2
duration_secs = 222

[[entry]]
played_at = "2026-07-05T18:04:07Z"
path = "spotify:track:7vBW7vVdCDxFa0UeVPM549"
title = "Научиться бы не париться"
artist = "Gradusy"
album = "Научиться бы не париться"
year = 2012
track_number = 1
duration_secs = 208
