[[entry]]
played_at = "2026-07-05T18:40:16Z"
path = "spotify:track:4NkCOiUOXDXrPWeuQJE6cl"
title = "Кустурица"
artist = "Bratya Grim"
album = "Братья Грим"
year = 2005
track_number = 12
duration_secs = 173

[[entry]]
played_at = "2026-07-05T18:27:46Z"
path = "spotify:track:4wwqUoX7OweabhkpP2kaTS"
title = "ХОЧЕШЬ?"
artist = "Zemfira"
album = "ПРОСТИ МЕНЯ МОЯ ЛЮБОВЬ"
year = 2000
track_number = 4
duration_secs = 198

[[entry]]
played_at = "2026-07-05T18:10:29Z"
path = "spotify:track:4NkCOiUOXDXrPWeuQJE6cl"
title = "Кустурица"
artist = "Bratya Grim"
album = "Братья Грим"
year = 2005
track_number = 12
duration_secs = 173

[[entry]]
played_at = "2026-07-05T18:06:46Z"
path = "spotify:track:2pQZkGyZvrep3yAAlBKsdX"
title = "Ночь"
artist = "Andrey Gubin"
album = "Мальчик бродяга"
year = 1995
track_number = 2
duration_secs = 222

[[entry]]
played_at = "2026-07-05T18:04:07Z"
path = "spotify:track:7vBW7vVdCDxFa0UeVPM549"
title = "Научиться бы не париться"
artist = "Gradusy"
album = "Научиться бы не париться"
year = 2012
track_number = 1
duration_secs = 208
