ecosystem {
  enforce_permissions = yes
}

permission = /bin/grim, screencopy, allow

# dont actually work but for some reasons reduces the number of notifications
permission = /home/rahman/Arch-dotfiles/scripts/screenshot.sh, screencopy, allow
permission = /home/rahman/Arch-dotfiles/scripts/screenshot-full.sh, screencopy, allow


permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(bin|local/bin)/hyprpm, plugin, ask
